version: '3'

services:
  nginx:
    container_name: hd_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app

  db:
    container_name: hd_db
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hd_laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - "9906:3306"

  app:
    container_name: hd_app
    build:
      context: .
      dockerfile: _docker/php/Dockerfile
    volumes:
      - ./:/var/www
